<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="9285" started-at="2019-10-22T09:59:10Z" finished-at="2019-10-22T09:59:19Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="9285" started-at="2019-10-22T09:59:10Z" finished-at="2019-10-22T09:59:19Z">
      <class name="Drivers.ExtendReportsDemo">
        <test-method status="PASS" signature="StartReport()[pri:0, instance:Drivers.ExtendReportsDemo@724af044]" name="StartReport" is-config="true" duration-ms="206" started-at="2019-10-22T15:29:10Z" finished-at="2019-10-22T15:29:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- StartReport -->
        <test-method status="FAIL" signature="login()[pri:0, instance:Drivers.ExtendReportsDemo@724af044]" name="login" duration-ms="8212" started-at="2019-10-22T15:29:10Z" finished-at="2019-10-22T15:29:18Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Demo Web Shop] but found [Srinivas]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Demo Web Shop] but found [Srinivas]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at org.testng.Assert.assertEquals(Assert.java:199)
	at Drivers.ExtendReportsDemo.login(ExtendReportsDemo.java:46)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method status="PASS" signature="getResult(org.testng.ITestResult)[pri:0, instance:Drivers.ExtendReportsDemo@724af044]" name="getResult" is-config="true" duration-ms="486" started-at="2019-10-22T15:29:18Z" finished-at="2019-10-22T15:29:18Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=login status=FAILURE method=ExtendReportsDemo.login()[pri:0, instance:Drivers.ExtendReportsDemo@724af044] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
        <test-method status="PASS" signature="testCase1()[pri:0, instance:Drivers.ExtendReportsDemo@724af044]" name="testCase1" duration-ms="2" started-at="2019-10-22T15:29:18Z" finished-at="2019-10-22T15:29:18Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCase1 -->
        <test-method status="PASS" signature="getResult(org.testng.ITestResult)[pri:0, instance:Drivers.ExtendReportsDemo@724af044]" name="getResult" is-config="true" duration-ms="3" started-at="2019-10-22T15:29:18Z" finished-at="2019-10-22T15:29:19Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testCase1 status=SUCCESS method=ExtendReportsDemo.testCase1()[pri:0, instance:Drivers.ExtendReportsDemo@724af044] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:Drivers.ExtendReportsDemo@724af044]" name="tearDown" is-config="true" duration-ms="346" started-at="2019-10-22T15:29:19Z" finished-at="2019-10-22T15:29:19Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- Drivers.ExtendReportsDemo -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
